#!/bin/sh
# - runtime
# - test
# - nr_task

## UnixBench is the original BYTE UNIX benchmark suite. The purpose
## of UnixBench is to provide a basic indicator of the performance
## of a Unix-like system; hence, multiple tests are used to test
## various aspects of the system's performance.

. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/run.sh

cd_benchmark

if [ "$need_x" = true ]; then
	mkdir -p /tmp/.X11-unix
	chmod 1777 /tmp/.X11-unix
	chown root:root /tmp/.X11-unix

	xinit $LKP_SRC/programs/unixbench/xinitrc 2>&1
	exit_status=$?

	xinitrc_exit_status_file=/tmp/unixbench.xinitrc.exit-status
	[ -f "$xinitrc_exit_status_file" ] && {
		exit_status=$(cat $xinitrc_exit_status_file)
		rm -vf $xinitrc_exit_status_file
	}
else
	$LKP_SRC/programs/unixbench/xinitrc
	exit_status=$?
fi

exit $exit_status
