#!/bin/bash
# - test
# - nvme_trtype
# - use_siw

## blktests is a test framework for the Linux kernel block layer and storage stack.

. $LKP_SRC/lib/env.sh
. $LKP_SRC/lib/job.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/upload.sh
. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/tests/common.sh
. $LKP_SRC/lib/run.sh

cd_benchmark

# https://github.com/osandov/blktests/pull/64
sed -i 's/set -u//' common/multipath-over-rdma

setup_nvme_cli()
{
	local base_dir="$(get_benchmark_path)"
	local bindir="$base_dir/bin"
	local libdir="$base_dir/lib"

	[[ -x "$bindir/nvme" ]] || return

	export PATH="$bindir:$PATH"
	export LD_LIBRARY_PATH="$libdir:$LD_LIBRARY_PATH"
}

enable_nvme_auth()
{
	# fix nvme-fabrics does not support dhchap_ctrl_secret issue
	local modules=(
		nvme-fabrics
		nvme-keyring
		nvme-auth
	)

	case "$nvme_trtype" in
	rdma)
		modules+=(nvme-rdma)
		[[ "$use_siw" == "true" ]] && modules+=(siw)
		;;
	tcp)
		modules+=(nvme-tcp)
		;;
	esac

	local module
	for module in "${modules[@]}"; do
		log_cmd modprobe "$module" 2>&1 || true
	done
}

set_env()
{
	local partition
	case "$test" in
	nbd-*|loop-*)
		partition=""
		;;
	scsi-*|block-*)
		partition=${partitions%% *}
		# block/019 and block/011 need a whole disk to test PCI hotplug
		if [[ "$test" == "block-019" ]] || [[ "$test" == "block-011" ]] || is_virt; then
			if [[ "$partition" =~ nvme ]]; then
				# strip 'p1' from 'nvme0n1p1'
				partition=${partition%p[0-9]*}
			else
				# strip '1' from 'sda1'
				partition=${partition%%[0-9]*}
			fi
		fi
		[[ "$test" == "block-004" ]] && log_eval export TIMEOUT=300
		;;
	srp-*)
		log_cmd systemctl stop multipathd
		;;
	zbd-*)
		partition=${partitions%% *}
		# fix the issue: /etc/fscrypt.conf is missing
		if [[ ! -f /etc/fscrypt.conf ]] && has_cmd fscrypt; then
			fscrypt setup --force # --quiet
		fi
		;;
	*)
		partition=${partitions%% *}
		;;
	esac

	if [[ -n "$partition" ]]; then
		echo "TEST_DEVS=$partition" > config
		if [[ "${test%%-*}" == "nvme" ]]; then
			enable_nvme_auth

			log_cmd mkdir -p /mnt/$test && log_cmd mount $partition /mnt/$test
		else
			umount "${partition}"* 2>/dev/null || true
		fi
	fi

	[[ "$nvme_trtype" ]] && echo "nvme_trtype=$nvme_trtype" >> config
	[[ "$use_siw" == "true" ]] && echo "use_siw=1" >> config

	# fix the issue: losetup: cannot find an unused loop device
	lsmod | grep -q loop || modprobe loop

	# fix blkzone is not available
	ln -sf $BENCHMARK_ROOT/blktests/util-linux/blkzone /usr/bin/blkzone
}

run_test()
{
	local test_dir="$BENCHMARK_ROOT/blktests/tests"
	local all_tests

	if [[ "$test" =~ -[0-9]{3}$ ]]; then # single test
		all_tests="${test%-*}/${test##*-}"
		log_echo "echo $all_tests"
	elif [[ "$test" == *-* ]]; then # group tests
		local group="${test%%-*}"
		log_echo "sed \"s:^:${group}/:\" $test_dir/$test"
		all_tests=$(sed "s:^:${group}/:" "$test_dir/$test")
	else
		all_tests="$test"
	fi

	[[ -z "$all_tests" ]] && die "no tests found for $test"

	local args=()
	[[ "$test" == nvme-* ]] && args+=(-o "/mnt/$test")

	local tests_array=()
	mapfile -t tests_array <<< "$all_tests"
	args+=("${tests_array[@]}")

	log_cmd ./check "${args[@]}"
}

read_env_vars
setup_nvme_cli
set_env
run_test

[[ -d "$BENCHMARK_ROOT/blktests/results" ]] && upload_files -t results $BENCHMARK_ROOT/blktests/results/*
[[ -d "/mnt/$test/nodev" ]] && upload_files -t results /mnt/$test/nodev/*

exit 0
