require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/AmbiguousRange:
  Enabled: false

Lint/FloatComparison:
  Enabled: false

Lint/OrAssignmentToConstant:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/ToEnumArguments:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Metrics/AbcSize:
  Max: 50
  Exclude:
    - lib/changed_stat.rb
    - lib/compare.rb
    - lib/job.rb
    - lib/job2sh.rb
    - lib/matrix.rb
    - lib/plot.rb
    - lib/stats.rb
    - sbin/compare

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 30 # 6 by default
  Exclude:
    - lib/job2sh.rb
    - lib/matrix.rb
    - lib/stats.rb
    - sbin/compare

Metrics/MethodLength:
  Max: 50
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 30
  Exclude:
    - lib/job2sh.rb
    - lib/matrix.rb
    - lib/stats.rb
    - sbin/compare

Naming/AccessorMethodName:
  Exclude:
    - 'lib/property.rb'

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Performance/CollectionLiteralInLoop:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Performance/StringInclude:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/LeakyLocalVariable:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NoExpectationExample:
  AllowedPatterns:
    - ^expect_
    - ^verify_

Security/Eval:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Style/FloatDivision:
  Exclude:
    - 'programs/pmbench/parse'

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/NumericPredicate:
  Exclude:
    - 'lib/job2sh.rb'
    - 'lib/matrix.rb'
    - 'lib/stats.rb'

Style/OpenStructUse:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

