#!/bin/sh
# - nr_threads
# - protocol
# - winsize
# - runtime
# - datasize

. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/run.sh

run_uperf()
{
	cd_benchmark

	log_cmd uperf -m uperf_web.xml
}

prepare_exec_path

run_uperf
