#!/bin/sh

. $LKP_SRC/lib/detect-system.sh
arch=$(get_system_arch)

# enable i386 arch packages
[ "$arch" = "x86_64" ] && dpkg --add-architecture i386 && apt-get update
# shellcheck disable=SC2048
yes "" | DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confdef" \
	-o Dpkg::Options::="--force-confold" \
	-o Dpkg::Options::="--force-overwrite" \
	-y install $*
