#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.dirname(File.dirname(File.realpath($PROGRAM_NAME))))

require "#{LKP_SRC}/lib/string"
require "#{LKP_SRC}/lib/tests/stats"

stats = LKP::Stats.new

while (line = $stdin.gets)
  line = line.resolve_invalid_bytes.uncolorize

  # ftrace_regression01: pass | tainted  (1.585s)
  next unless line =~ /^(.+): (pass|fail|broken|warn|conf|skip) | .+ \(.+s\)/

  stats.add $1, $2, overwrite: true
end

stats.dump
