#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.realpath($PROGRAM_NAME), 3)

require "#{LKP_SRC}/lib/string"
require "#{LKP_SRC}/lib/tests/stats"

stats = LKP::Stats.new

while (line = $stdin.gets)
  line = line.resolve_invalid_bytes.uncolorize

  break if line.strip == 'LTP test details'

  # ftrace_regression01: pass | tainted  (1.585s)
  # landlock04: skip | tainted  (2m 40s)
  # cacheflush01: skip  (0.003s)
  # cachestat01: pass  (1.210s)
  next unless line =~ /^(.+?):\s+(pass|fail|broken|warn|conf|skip)(?: \| .+)?\s+\(.+s\)/

  stats.add $1, $2, overwrite: true
end

stats.dump
