#!/bin/bash
# - test

## The LTP testsuite contains a collection of tools for
## testing the Linux kernel and related features.

. $LKP_SRC/lib/env.sh
. $LKP_SRC/lib/upload.sh
. $LKP_SRC/lib/tests/ltp.sh
. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/run.sh

prepare_exec_path kirk

cd_benchmark

fixup_env
fixup_test $test

create_single_test_file $test
is_excluded $test

log_cmd export LTP_RUNTIME_MUL=2
log_cmd export LTPROOT="$(get_benchmark_path)" # used by kirk

if [[ -f "$BENCHMARK_ROOT/ltp/runtest/$test" ]]; then
    log_cmd kirk -f $test $big_dev_opt $tmpdir_opt
elif [[ -f "$BENCHMARK_ROOT/ltp/runtest/temp_single_test" ]]; then
    log_cmd kirk -f temp_single_test $big_dev_opt $tmpdir_opt
else
    die "ltp test cmdfile is not found"
fi

cleanup_ltp $test

kirk_latest="/tmp/kirk.$(whoami)/latest"
kirk_results_json="$kirk_latest/results.json"

if [[ -d "$kirk_latest" ]]; then
    if [[ -f "$kirk_results_json" ]]; then
        echo "LTP test details"
        echo "----------------"

        if ! jq -r '.results[]? as $r | ($r.test.log? // "" | split("\n") | map(select(test("TFAIL|TBROK|TWARN|TCONF"))) | unique) as $details | select((($r.status // "") != "pass") or (($details | length) > 0)) | if ($details | length) > 0 then $details[] | "\($r.test_fqn): \(.)" else "\($r.test_fqn): \($r.status)" end' "$kirk_results_json"; then
            echo "Failed to parse $kirk_results_json by jq" 1>&2
        fi
    fi

    upload_files -t results "$kirk_latest"/* 2>&1
else
    echo "$kirk_latest is not found"
fi

exit 0
