#!/usr/bin/env ruby

class YcsbParser
  def initialize
    @results_total = {}
  end

  def parse(line)
    case line
    when /OVERALL/, /TOTAL/
      parse_overall_total(line)
    when /READ/
      parse_read_ops(line)
    when /CLEANUP/
      parse_cleanup(line)
    when /INSERT/
      parse_insert(line)
    else
      parse_misc(line)
    end
  end

  def parse_overall_total(line)
    case line
    when /OVERALL\W, RunTime.ms., (\d+)$/
      add_result('runtime', $1.to_f)
    when /OVERALL\W, Throughput.ops.sec., (\d+\.\d+)$/
      add_result('throughput_ops/s', $1.to_f)
    when /TOTAL_GCS_G1_Young_Generation\W, Count, (\d+)$/
      add_result('gcs_g1', $1.to_f)
    when /TOTAL_GC_TIME_G1_Young_Generation\W, Time.ms., (\d+)$/
      add_result('gc_time_g1', $1.to_f)
    when /TOTAL_GC_TIME_%_G1_Young_Generation\W, Time.%., (\d+\.\d+)$/
      add_result('gc_time_%', $1.to_f)
    when /TOTAL_GCS_G1_Old_Generation\W, Count, (\d+)$/
      add_result('gcs_g1_old', $1.to_f)
    when /TOTAL_GC_TIME_G1_Old_Generation\W, Time.ms., (\d+)$/
      add_result('gc_time_g1_old', $1.to_f)
    when /TOTAL_GC_TIME_%_G1_Old_Generation\W, Time.%., (\d+\.\d+)$/
      add_result('gc_time_%_old', $1.to_f)
    when /TOTAL_GCs\W, Count, (\d+)$/
      add_result('total_gcs', $1.to_f)
    when /TOTAL_GC_TIME\W, Time.ms., (\d+)$/
      add_result('total_gc_time', $1.to_f)
    when /TOTAL_GC_TIME_%\W, Time.%., (\d+\.\d+)$/
      add_result('total_gc_time_%', $1.to_f)
    end
  end

  def parse_read_ops(line)
    case line
    when /READ\W, Operations, (\d+)$/
      add_result('read_operations', $1.to_f)
    when /READ\W, AverageLatency.us., (\d+\.\d+)$/
      add_result('read_averagelatency', $1.to_f)
    when /READ\W, MinLatency.us., (\d+)$/
      add_result('read_minlatency', $1.to_f)
    when /READ\W, MaxLatency.us., (\d+)$/
      add_result('read_maxlatency', $1.to_f)
    when /READ\W, 95thPercentileLatency.us., (\d+)$/
      add_result('read_95%latency', $1.to_f)
    when /READ\W, 99thPercentileLatency.us., (\d+)$/
      add_result('read_99%latency', $1.to_f)
    when /READ\W, Return=OK, (\d+)$/
      add_result('read_return_ok', $1.to_f)
    when /READ\W, Return=NOT_FOUND, (\d+)$/
      add_result('read_return_notfound', $1.to_f)
    when /READ-FAILED\W, Operations, (\d+)$/
      add_result('read_failed_operations', $1.to_f)
    when /READ-FAILED\W, AverageLatency.us., (\d+\.\d+)$/
      add_result('read_failed_averagelatency', $1.to_f)
    when /READ-FAILED\W, MinLatency.us., (\d+)$/
      add_result('read_failed_minlatency', $1.to_f)
    when /READ-FAILED\W, MaxLatency.us., (\d+)$/
      add_result('read_failed_maxlatency', $1.to_f)
    when /READ-FAILED\W, 95thPercentileLatency.us., (\d+)$/
      add_result('read_failed_95%latency', $1.to_f)
    when /READ-FAILED\W, 99thPercentileLatency.us., (\d+)$/
      add_result('read_failed_99%latency', $1.to_f)
    end
  end

  def parse_cleanup(line)
    case line
    when /CLEANUP\W, Operations, (\d+)$/
      add_result('cleanup_operations', $1.to_f)
    when /CLEANUP\W, AverageLatency.us., (\d+\.\d+)$/
      add_result('cleanup_averagelatency', $1.to_f)
    when /CLEANUP\W, MinLatency.us., (\d+)$/
      add_result('cleanup_minlatency', $1.to_f)
    when /CLEANUP\W, MaxLatency.us., (\d+)$/
      add_result('cleanup_maxlatency', $1.to_f)
    when /CLEANUP\W, 95thPercentileLatency.us., (\d+)$/
      add_result('cleanup_95%latency', $1.to_f)
    when /CLEANUP\W, 99thPercentileLatency.us., (\d+)$/
      add_result('cleanup_99%latency', $1.to_f)
    end
  end

  def parse_insert(line)
    case line
    when /INSERT\W, Operations, (\d+)$/
      add_result('insert_operations', $1.to_f)
    when /INSERT\W, AverageLatency.us., (\d+\.\d+)$/
      add_result('insert_averagelatency', $1.to_f)
    when /INSERT\W, MinLatency.us., (\d+)$/
      add_result('insert_minlatency', $1.to_f)
    when /INSERT\W, MaxLatency.us., (\d+)$/
      add_result('insert_maxlatency', $1.to_f)
    when /INSERT\W, 95thPercentileLatency.us., (\d+)$/
      add_result('insert_95%latency', $1.to_f)
    when /INSERT\W, 99thPercentileLatency.us., (\d+)$/
      add_result('insert_99%latency', $1.to_f)
    when /INSERT\W, Return=OK, (\d+)$/
      add_result('insert_return_ok', $1.to_f)
    when /INSERT\W, Return=ERROR, (\d+)$/
      add_result('insert_return_error', $1.to_f)
    when /INSERT-FAILED\W, Operations, (\d+)$/
      add_result('insert_failed_operations', $1.to_f)
      puts "insert_failed_operations: #{$1}"
    when /INSERT-FAILED\W, AverageLatency.us., (\d+\.\d+)$/
      add_result('insert_failed_averagelatency', $1.to_f)
    when /INSERT-FAILED\W, MinLatency.us., (\d+)$/
      add_result('insert_failed_minlatency', $1.to_f)
      puts "insert_failed_minlatency: #{$1}"
    when /INSERT-FAILED\W, MaxLatency.us., (\d+)$/
      add_result('insert_failed_maxlatency', $1.to_f)
    when /INSERT-FAILED\W, 95thPercentileLatency.us., (\d+)$/
      add_result('insert_failed_95%latency', $1.to_f)
    when /INSERT-FAILED\W, 99thPercentileLatency.us., (\d+)$/
      add_result('insert_failed_99%latency', $1.to_f)
    end
  end

  def parse_misc(line)
    return unless line =~ /^preload duration: (\d+\.\d+)$/

    puts "preload_duration: #{$1}"
  end

  def add_result(key, val)
    @results_total[key] ||= []
    @results_total[key] << val
  end

  def print_summary
    @results_total.each do |key, vals|
      puts "total_#{key}: #{vals.sum(0.0)}"
    end

    @results_total.each do |key, vals| # rubocop:disable Style/CombinableLoops
      puts "avg_#{key}: #{vals.sum(0.0) / vals.length}"
    end
  end
end

parser = YcsbParser.new
$stdin.each_line do |line|
  parser.parse(line)
end
parser.print_summary
