#!/bin/sh

. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/run.sh

## Blogbench is a portable filesystem benchmark that tries to
## reproduce the load of a real-world busy file server.

cd_benchmark

log_cmd ./blogbench -d ${mount_points%% *}
