#!/bin/sh
# - workload

. $LKP_SRC/lib/upload.sh
. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/run.sh

prepare_exec_path

cd_benchmark

log_cmd rt-app workloads/${workload}.json 2>&1

log_cmd find . -print -name "*.log" -exec cat {} \;

upload_files -t results $(get_benchmark_path)/*.log
