#!/bin/bash
# - test

## Regression test suite for xfs and other filesystems.

. $LKP_SRC/lib/job.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/upload.sh
. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/tests/common.sh
. $LKP_SRC/lib/tests/xfstests.sh
. $LKP_SRC/lib/env.sh
. $LKP_SRC/lib/run.sh

[ "$nr_partitions" -lt 2 ] && die "$nr_partitions -lt 2"

cd_benchmark

export LC_ALL=C
export LANG=C
# whether has created the virtual disk
has_virtual_disk=false
read_env_vars
set_env || exit
run_test || die "fail to run test"

# umonut the virtual disk
[ "$has_virtual_disk" = true ] && losetup -d /dev/loop0
upload_files -t results $BENCHMARK_ROOT/xfstests/results/*
