#!/bin/sh
# - arrival_rate
# - num_loop
# - service_time
# - nr_threads

. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/run.sh

cd_benchmark

: "${arrival_rate:=2000}"
: "${num_loop:=200000}"
: "${service_time:=2000}"
: "${nr_threads:=1}"

log_cmd ./adrestia -a $arrival_rate -l $num_loop -s $service_time -t $nr_threads
