#!/bin/sh
# - nr_threads

## DBENCH is a tool to generate I/O workloads to either a filesystem
## or to a networked CIFS or NFS server. It generates load patterns
## similar to those of the commercial Netbench benchmark, but without
## requiring a lab of Windows load generators to run.
##
## Homepage: https://dbench.samba.org/

. $LKP_SRC/lib/env.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/run.sh

run_dbench()
{
	load_file=loadfiles/client.load
	[ -f "$load_file" ] || die "can not find $load_file"

	log_cmd dbench $nr_threads -c $load_file
}

run_cifsdbench()
{
	# https://dbench.samba.org/loadfiles/smb.load
	# dbench -B smb --smb-share=//10.0.0.33/data --smb-user=Administrator%password --loadfile=smb-writefiles.load --run-once --skip-cleanup 10
	# dbench version 4.00 - Copyright Andrew Tridgell 1999-2004

	log_cmd umount $cifs_mount_points
	# First run is used to avoid below errors, it will be prepare files for next 2nd run
	# [5] OPEN "client7/test.load" failed
	# drop its output, otherwise it will confuse the stat
	echo "dbench -B smb --smb-share=\"$cifs_server_paths\" --smb-user=root%pass --loadfile=loadfiles/smb_3.load -t 60 --skip-cleanup  $nr_threads"
	dbench -B smb --smb-share="$cifs_server_paths" --smb-user=root%pass --loadfile=loadfiles/smb_3.load -t 60 --skip-cleanup $nr_threads 1>/dev/null 2>&1

	sleep 2

	load_file=loadfiles/smb_2.load
	[ -f "$load_file" ] || die "can not find $load_file"

	log_cmd dbench -B smb --smb-share="$cifs_server_paths" --smb-user=root%pass --loadfile=$loadfiles -t 60 --skip-cleanup $nr_threads
}

run_nfsdbench()
{
	# https://dbench.samba.org/web/nfs-loadfiles.html
	# dbench -B nfs --server=10.0.0.21 --export=/gpfs/nfsshare --protocol=tcp -c tmp.loadfile  -t 20 3 2>/dev/null
	log_cmd umount $nfs_mount_points

	load_file=loadfiles/nfs_2.load
	[ -f "$load_file" ] || die "can not find $load_file"

	log_cmd dbench -B nfs --server=127.0.0.1 --export=/export"$nfs_export_paths" --protocol=tcp --loadfile=$load_file -t 60 $nr_threads
}

prepare_exec_path

dbench --help

cd_benchmark

run_"$fs2"dbench
