#!/bin/sh
# - nr_loops
# - nr_threads

. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/run.sh

cd_benchmark

cd linux || die "linux kernel source not found"

../kernbench -n $nr_loops -o $nr_threads -H -M -f
