#!/bin/bash
# - paranoid

## perf_event_tests is designed to test trinity for perf
## See: https://github.com/deater/perf_event_tests

. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/tests/perf_event_tests.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/run.sh

cd_benchmark

check_elements "$paranoid"
setup_test_env "$paranoid"

log_cmd ./run_tests.sh

clean_test_env
