#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.realpath($PROGRAM_NAME), 3)

require "#{LKP_SRC}/lib/string"

stats_name = 'fail: 1'

while (line = $stdin.gets)
  line = line.resolve_invalid_bytes

  case line
  when /^SUSPEND RESUME TEST SUCCESS/
    stats_name = 'pass: 1'
    break
  end
end

puts stats_name
