#!/usr/bin/env ruby

MAX_COLS = 100

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.realpath($PROGRAM_NAME), 2)

require "#{LKP_SRC}/lib/job"
require "#{LKP_SRC}/lib/matrix"

result_root = ARGV[0] || ENV.fetch('RESULT_ROOT', nil)

unite_params result_root
