#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.realpath($PROGRAM_NAME), 2)

require 'optparse'
require "#{LKP_SRC}/lib/job"
require "#{LKP_SRC}/lib/lkp_git"
require "#{LKP_SRC}/lib/matrix"
require "#{LKP_SRC}/lib/statistics"
require "#{LKP_SRC}/lib/stats"
require "#{LKP_SRC}/lib/yaml"

File.umask 0o002

delete = false

opt_parser = OptionParser.new do |opts|
  opts.banner = 'Usage: unite-stats [-d] [RESULT_ROOT]'
  opts.separator ''
  opts.separator 'options:'

  opts.on('-d', '--delete', 'Delete this RESULT_ROOT') do
    delete = true
  end

  opts.on_tail('-h', '--help', 'Show this message') do
    puts opts
    exit
  end
end

opt_parser.parse!(ARGV)

result_root = ARGV[0] || ENV.fetch('RESULT_ROOT', nil)

unite_stats result_root, delete: delete
