#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.realpath($PROGRAM_NAME), 3)

require "#{LKP_SRC}/lib/statistics"

class SchbenchParser
  def initialize
    @wakeupstats = Hash.new { |h, k| h[k] = [] }
    @wakeup_end_latency = Hash.new { |h, k| h[k] = [] }
    @requeststats = Hash.new { |h, k| h[k] = [] }
    @request_end_latency = Hash.new { |h, k| h[k] = [] }
    @counter = -1
    @in_wakeup_section = false
    @in_request_section = false
  end

  def parse(line)
    case line
    when /^Iteration/
      @counter += 1
    when /^Wakeup Latencies percentiles/
      @in_wakeup_section = true
      @in_request_section = false
    when /^Request Latencies percentiles/
      @in_wakeup_section = false
      @in_request_section = true
    when /^RPS percentiles/
      @in_wakeup_section = false
      @in_request_section = false
    when /50.0th/
      add_stat('latency_50%_us', line.split[1].to_i)
    when /90.0th/
      add_stat('latency_90%_us', line.split[1].to_i)
    when /99.0th/
      add_stat('latency_99%_us', line.split[2].to_i)
    when /99.9th/
      add_stat('latency_99.9%_us', line.split[1].to_i)
    when /min/
      handle_min(line)
    end
  end

  def add_stat(key, value)
    if @in_wakeup_section
      @wakeupstats[key] << value
      @wakeup_end_latency[key][@counter] = value
    elsif @in_request_section
      @requeststats[key] << value
      @request_end_latency[key][@counter] = value
    end
  end

  def handle_min(line)
    parts = line.gsub(/([,=])/, ' ').split
    key1 = "latency_#{parts[0]}_us"
    val1 = parts[1].to_i
    key2 = "latency_#{parts[2]}_us"
    val2 = parts[3].to_i

    if @in_wakeup_section
      @wakeupstats[key1] << val1
      @wakeupstats[key2] << val2
    elsif @in_request_section
      @requeststats[key1] << val1
      @requeststats[key2] << val2
    end
  end

  def print_summary
    @wakeupstats.each do |k, v|
      puts "wakeup_#{k}: #{v.average.round(2)}"
      puts "wakeup_#{k}_stddev%: #{v.relative_stddev.round(2)}"
    end

    @wakeup_end_latency.each do |k, v|
      puts "wakeup_end_#{k}_max: #{v.max}"
      puts "wakeup_end_#{k}_stddev%: #{v.relative_stddev.round(2)}"
    end

    @requeststats.each do |k, v|
      puts "request_#{k}: #{v.average.round(2)}"
      puts "request_#{k}_stddev%: #{v.relative_stddev.round(2)}"
    end

    @request_end_latency.each do |k, v|
      puts "request_end_#{k}_max: #{v.max}"
      puts "request_end_#{k}_stddev%: #{v.relative_stddev.round(2)}"
    end
  end
end

parser = SchbenchParser.new
$stdin.each_line do |line|
  parser.parse(line)
end
parser.print_summary
