#!/bin/bash
# - runtime
# - algorithm

. $LKP_SRC/lib/upload.sh
. $LKP_SRC/lib/unit.sh
. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/run.sh

cd_benchmark

echo "Running openssl-speed benchmark..."
export LD_LIBRARY_PATH=$BENCHMARK_ROOT/openssl/lib:$LD_LIBRARY_PATH
log_cmd ./apps/openssl speed -multi $(nproc) -seconds $runtime $algorithm

