#!/bin/bash
# - test
# - group

. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/tests/nvml.sh
. $LKP_SRC/lib/run.sh

cd_benchmark

check_group_param
check_test_param

setup_compiler

build_env

enable_remote_node

run
