#!/bin/bash
# - input_dir
# - output_dir

## Use dia command to transform dia to png image

. $LKP_SRC/lib/env.sh

install_pkg()
{
	has_cmd dia || {
		apt-get update
		apt-get -f -y install
		apt-get -o Dpkg::Options::="--force-confdef" \
			-o Dpkg::Options::="--force-confold" \
			-y install dia
	}

}

generate_png()
{
	# shellcheck disable=SC2154
	dia_files="$(find $input_dir -name '*.dia')"
	upper_dir=

	for file in $dia_files
	do
		upper_dir="$(echo $file | awk -F'/' '{printf("%s",$(NF-1))}')"
		output_dir="$output_dir/$upper_dir"
		[ -d $output_dir ] || mkdir -p $output_dir
		dia -t png $file -O $output_dir
	done
}

install_pkg
generate_png
