#!/bin/sh
# - runtime

## Measuring latency in the Linux network stack between kernel and user space.

. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/run.sh

cd_benchmark

[ -n "$runtime" ] || runtime=300

./ku-latency -e localhost &
LATENCY_PID=$!

./send-data -d localhost &
DATA_PID=$!

sleep $runtime

kill -INT $DATA_PID
kill $LATENCY_PID
