#!/bin/bash

# wake those detached processes up to do read
# shellcheck disable=SC2046
kill -USR1 $(cat $TMP/pidfile)

any_pid_alive()
{
	local pidfile=$1
	while read -r pid || [[ -n "$pid" ]]; do
		[[ -n "$pid" ]] || continue
		test -d "/proc/$pid" && return
	done < "$pidfile"
	return 1
}

# wait till those detached processes exit
while true
do
	sleep 5
	any_pid_alive $TMP/pidfile && continue
	break
done

rm $TMP/pidfile

# lkp will complain if the test doesn't generate any output
echo "test done"
