#!/bin/sh
# - rounds
# - warp

. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/run.sh

cd_benchmark

log_cmd python3 pybench.py -n $rounds -w $warp || die "failed to run pybench"
