#!/bin/sh
# - priority
# - clock
# - interval
# - histogram
# - loops

. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/run.sh

run_test()
{
	log_cmd cyclictest -p $priority -m -c $clock -i $interval -h $histogram -q -l $loops 2>&1
}

prepare_exec_path
run_test
