#!/bin/sh

export_top_env()
{
	export suite='mytest'
	export testcase='mytest'
	export job_origin='monitor.yaml'
	export testbox=''
	export arch=''
	export tbox_group=''
	export kconfig=''
	export compiler=''
	export commit=''
	export rootfs=''
	export nr_cpu=
	export memory=''
	export NO_NETWORK=1
	export LKP_LOCAL_RUN=1
	export result_root_template="/lkp/result/mytest/\$opt_test_name/\$testbox/\$rootfs/\$kconfig/\$compiler/\$commit"
}

run_job()
{
	echo $$ >$TMP/run-job.pid

	. $LKP_SRC/lib/http.sh
	. $LKP_SRC/lib/job.sh
	. $LKP_SRC/lib/env.sh

	run_monitor $LKP_SRC/bin/run-monitor iostat
	run_monitor $LKP_SRC/bin/run-monitor vmstat
	run_monitor $LKP_SRC/bin/run-monitor numa-numastat
	run_monitor $LKP_SRC/bin/run-monitor numa-vmstat
	run_monitor $LKP_SRC/bin/run-monitor numa-meminfo
	run_monitor $LKP_SRC/bin/run-monitor proc-vmstat
	run_monitor $LKP_SRC/bin/run-monitor proc-stat
	run_monitor $LKP_SRC/bin/run-monitor meminfo
	run_monitor $LKP_SRC/bin/run-monitor slabinfo
	run_monitor $LKP_SRC/bin/run-monitor interrupts
	run_monitor $LKP_SRC/bin/run-monitor lock_stat
	run_monitor lite_mode=1 $LKP_SRC/bin/run-monitor perf-sched
	run_monitor $LKP_SRC/bin/run-monitor softirqs
	run_monitor $LKP_SRC/bin/run-monitor diskstats
	run_monitor $LKP_SRC/bin/run-monitor cpuidle
	run_monitor $LKP_SRC/bin/run-monitor cpufreq-stats
	run_monitor $LKP_SRC/bin/run-monitor turbostat
	run_monitor $LKP_SRC/bin/run-monitor sched_debug
	run_monitor $LKP_SRC/bin/run-monitor perf-stat
	run_monitor $LKP_SRC/bin/run-monitor mpstat
	run_monitor debug_mode=1 $LKP_SRC/bin/run-no-stdout-monitor perf-profile

	run_test $LKP_SRC/bin/run-test mytest
}

extract_stats()
{
	export stats_part_begin=
	export stats_part_end=

	$LKP_SRC/bin/run-stats iostat
	$LKP_SRC/bin/run-stats vmstat
	$LKP_SRC/bin/run-stats numa-numastat
	$LKP_SRC/bin/run-stats numa-vmstat
	$LKP_SRC/bin/run-stats numa-meminfo
	$LKP_SRC/bin/run-stats proc-vmstat
	$LKP_SRC/bin/run-stats meminfo
	$LKP_SRC/bin/run-stats slabinfo
	$LKP_SRC/bin/run-stats interrupts
	$LKP_SRC/bin/run-stats lock_stat
	env lite_mode=1 $LKP_SRC/bin/run-stats perf-sched
	$LKP_SRC/bin/run-stats softirqs
	$LKP_SRC/bin/run-stats diskstats
	$LKP_SRC/bin/run-stats cpuidle
	$LKP_SRC/bin/run-stats turbostat
	$LKP_SRC/bin/run-stats sched_debug
	$LKP_SRC/bin/run-stats perf-stat
	$LKP_SRC/bin/run-stats mpstat
	env debug_mode=1 $LKP_SRC/bin/run-stats perf-profile

	$LKP_SRC/bin/run-stats time mytest.time
	$LKP_SRC/bin/run-stats dmesg
	$LKP_SRC/bin/run-stats kmsg
	$LKP_SRC/bin/run-stats last_state
	$LKP_SRC/bin/run-stats stderr
	$LKP_SRC/bin/run-stats time
}

"$@"
