#!/bin/sh

export_top_env()
{
	export suite='mytest'
	export testcase='mytest'
	export category='benchmark'
	export job_origin='jobs/mytest.yaml'
	export testbox=''
	export arch=''
	export tbox_group=''
	export kconfig=''
	export compiler=''
	export commit=''
	export rootfs=''
	export nr_cpu=
	export memory=''
	export NO_NETWORK=1
	export LKP_LOCAL_RUN=1
	export result_root_template="/lkp/result/mytest/\$opt_test_name/\$testbox/\$rootfs/\$kconfig/\$compiler/\$commit"

	[ -n "$LKP_SRC" ] ||
		export LKP_SRC=/lkp/${user:-lkp}/src
}

run_job()
{
	echo $$ >$TMP/run-job.pid

	. $LKP_SRC/lib/http.sh
	. $LKP_SRC/lib/job.sh
	. $LKP_SRC/lib/env.sh

	run_monitor $LKP_SRC/bin/run-monitor numa-meminfo
	run_monitor $LKP_SRC/bin/run-monitor numa-vmstat
	run_monitor $LKP_SRC/bin/run-monitor slabinfo
	run_monitor $LKP_SRC/bin/run-monitor zoneinfo
	run_monitor $LKP_SRC/bin/run-monitor buddyinfo
	run_monitor $LKP_SRC/bin/run-monitor vmstat
	run_monitor $LKP_SRC/bin/run-monitor proc-vmstat
	run_monitor $LKP_SRC/bin/run-monitor meminfo
	run_monitor $LKP_SRC/bin/run-no-stdout-monitor perf-profile

	run_test $LKP_SRC/bin/run-test mytest
}

extract_stats()
{
	export stats_part_begin=
	export stats_part_end=

	$LKP_SRC/bin/run-stats numa-meminfo
	$LKP_SRC/bin/run-stats numa-vmstat
	$LKP_SRC/bin/run-stats slabinfo
	$LKP_SRC/bin/run-stats zoneinfo
	$LKP_SRC/bin/run-stats buddyinfo
	$LKP_SRC/bin/run-stats vmstat
	$LKP_SRC/bin/run-stats proc-vmstat
	$LKP_SRC/bin/run-stats meminfo
	$LKP_SRC/bin/run-stats perf-profile

	$LKP_SRC/bin/run-stats time mytest.time
	$LKP_SRC/bin/run-stats dmesg
	$LKP_SRC/bin/run-stats kmsg
	$LKP_SRC/bin/run-stats last_state
	$LKP_SRC/bin/run-stats stderr
	$LKP_SRC/bin/run-stats time
}

"$@"
