#!/bin/sh
# - thp_enabled
# - thp_defrag
# - shmem_enabled
# - enabled_64kB
# - enabled_32kB
# - enabled_16kB

. $LKP_SRC/lib/reproduce-log.sh

if [ -n "$thp_enabled" ]; then
	log_eval "echo '$thp_enabled' > /sys/kernel/mm/transparent_hugepage/enabled"
fi

if [ -n "$thp_defrag" ]; then
	log_eval "echo '$thp_defrag' > /sys/kernel/mm/transparent_hugepage/defrag"
fi

if [ -n "$shmem_enabled" ]; then
	log_eval "echo '$shmem_enabled' > /sys/kernel/mm/transparent_hugepage/shmem_enabled"
fi

if [ -n "$enabled_64kB" ]; then
	log_eval "echo '$enabled_64kB' > /sys/kernel/mm/transparent_hugepage/hugepages-64kB/enabled"
fi

if [ -n "$enabled_32kB" ]; then
	log_eval "echo '$enabled_32kB' > /sys/kernel/mm/transparent_hugepage/hugepages-32kB/enabled"
fi

if [ -n "$enabled_16kB" ]; then
	log_eval "echo '$enabled_16kB' > /sys/kernel/mm/transparent_hugepage/hugepages-16kB/enabled"
fi
